"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var producto_1 = require("./producto");
var kiosco_1 = require("./kiosco");
var alfajores = new producto_1.Producto('Alfajor Jorgito', 100, 25, 50);
var chocolates = new producto_1.Producto('CHocolate Milka', 250, 16, 100);
var chupetines = new producto_1.Producto('Chupetines Arcor', 20, 50, 75);
var pastillas = new producto_1.Producto('Pastillitas Yapa', 25, 25, 100);
var papitas = new producto_1.Producto('Papitas Lays', 235, 10, 65);
var galletitas = new producto_1.Producto('Galletitas Pepitos', 120, 7, 75);
var miKiosko = new kiosco_1.Kiosco;
miKiosko.agregarProducto(alfajores);
miKiosko.agregarProducto(chocolates);
miKiosko.agregarProducto(chupetines);
miKiosko.agregarProducto(pastillas);
miKiosko.agregarProducto(papitas);
miKiosko.agregarProducto(galletitas);
miKiosko.vender(alfajores, 5);
miKiosko.vender(chocolates, 2);
miKiosko.vender(pastillas, 7);
miKiosko.vender(galletitas, 8);
miKiosko.verStock();
miKiosko.verVentas();
